export const ADD_PAKEMON_TO_STATE = 'ADD_PAKEMON_TO_STATE'
export const CLEAR_STATE = 'CLEAR_STATE'
export const CONNETCTING_TO_API = 'CONNETCTING_TO_API'
export const GET_PAKEMON_LIST = 'GET_PAKEMON_LIST'
